FROM kubeflownotebookswg/jupyter-scipy:v1.9.2


USER root


RUN apt-get update && apt-get install -y --no-install-recommends \
    graphviz \
    && rm -rf /var/lib/apt/lists/*


USER jovyan


WORKDIR /home/jovyan


COPY --chown=jovyan:jovyan . .


RUN pip install --no-cache-dir --user .


CMD ["/bin/bash"]