name: Codecov upload
on:
  push:
    branches:
      - 'master'
jobs:
  codecov:
    name: Codecov Workflow
    runs-on: ubuntu-24.04
    
    steps:
      - uses: actions/checkout@v1
      - name: Set up Python
        uses: actions/setup-python@v2
        id: setup-python
        with:
          python-version: 3.11
      - name: Install uv
        uses: astral-sh/setup-uv@v1
        with:
          uv-version: 'latest'
      - name: Cache uv global directory
        uses: actions/cache@v4
        with:
          path: ${{ env.UV_CACHE_DIR }}
          key: ${{ runner.os }}-uv-3.11-${{ hashFiles('**/pyproject.toml') }}
          restore-keys: |
            ${{ runner.os }}-uv-3.11-
      - name: Generate coverage report
        run: |
          # Install project with test dependencies (includes pytest and pytest-cov)
          uv pip install ".[test]" --system
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
